var music = [
  {
    "title": "Eastside",
    "length_min": 2.53,
    "genre": "pop",
    "artist": ["Benny Blanco", " Halsey", " Khalid"],
    "year": 2018,
    "image" : "images/eastside.jpeg",
  },
  {
    "title": "Ocean Eyes",
    "length_min": 3.15,
    "genre": "pop",
    "artist": "Billie Eilish",
    "year": 2018,
    "image": "images/oceaneyes.jpeg",
  },
  {
    "title": "Andante, Andante",
    "length_min": 4.00,
    "genre": ["musical", " pop"],
    "artist": "Lily James",
    "year": 2018,
    "image" : "images/andante-1.jpeg",
  },
  {
    "title": "Frustrated",
    "length_min": 3.21,
    "genre": "pop",
    "artist": "R.LUM.R",
    "year": 2018,
    "image" : "images/frustrated.jpeg",
  },
  {
    "title": "Overwhelming",
    "length_min": 2.52,
    "genre": "pop",
    "artist": "Jon Bellion",
    "year": 2018,
    "image" : "images/overwhelming.jpeg",
  },
  {
    "title": "RIP",
    "length_min": 3.27,
    "genre": "pop",
    "artist": "Olivia O'Brien",
    "year": 2018,
    "image" : "images/rip.jpeg",
  },
  {
    "title": "The Weekend",
    "length_min": 2.51,
    "genre": "pop",
    "artist": ["SZA", " Calvin Harris", " Funk Wav"],
    "year": 2019,
    "image" : "images/theweekend.jpeg",
  },
  {
    "title": "24 / 7 / 365",
    "length_min": 2.57,
    "genre": "pop",
    "artist": "Surfaces",
    "year": 2019,
    "image": "images/247.jpeg",
  },
  {
    "title": "Heaven",
    "length_min": 3.11,
    "genre": "pop",
    "artist": "Julia Micheals",
    "year": 2018,
    "image": "images/heaven.jpeg",
  },
  {
    "title": "Best Friend",
    "length_min": 4.22,
    "genre": "pop",
    "artist": "Rex Orange Country",
    "year": 2018,
    "image": "images/bestfriend.jpeg",
  },
  {
    "title": "One Less Lonly Girl",
    "length_min": 3.49,
    "genre": "pop",
    "artist": "Justin Bieber",
    "year": 2009,
    "image" : "images/ollg-1.jpeg",
  },
  {
    "title": "A million dreams",
    "length_min": 4.29,
    "genre": ["pop", "musical"],
    "artist": ["Hugh Jackman", " Michelle Williams", " Zif Zalfman"],
    "year": 2018,
    "image" : "images/amilliondreams-1.jpeg",
  },
  {
    "title": "Live or die",
    "length_min": 3.14,
    "genre": "pop",
    "artist": ["Noah Cyrus", " Lil xan"],
    "year": 2018,
    "image": "images/liveordie.jpeg",
  },
  {
    "title": "Pete Davidson",
    "length_min": 1.53,
    "genre": "pop",
    "artist": "Ariana Grande",
    "year": 1018,
    "image": "images/pete.jpeg",
  },
  {
    "title": "Problems",
    "length_min": 3.39,
    "genre": "pop",
    "artist": ["Petit Biscuit", " Lido"],
    "year": 1972,
    "image": "images/problems.jpeg",
  },
  {
    "title": "One of Us",
    "length_min": 3.35,
    "genre": "pop",
    "artist": "Amanda Seyfried",
    "year": 2018,
    "image" : "images/oneofus.jpeg",
  },
  {
    "title": "Think about me",
    "length_min": 4.06,
    "genre": "pop",
    "artist": "dvsn",
    "year": 2018,
    "image": "images/thinkaboutme.jpeg",
  },
  {
    "title": "Without me",
    "length_min": 3.21,
    "genre": "pop",
    "artist": "Halsey",
    "year": 2018,
    "image": "images/withoutme.jpeg",
  },
  {
    "title": "Fall Back",
    "length_min": 3.16,
    "genre": "pop",
    "artist": "Cimorelli",
    "year": 2018,
    "image": "images/fallback.jpeg",
  },
  {
    "title": "Famous",
    "length_min": 3.43,
    "genre": "pop",
    "artist": "Ivy Adara",
    "year": 2018,
    "image": "images/famous.jpeg",
  },
  {
    "title": "Candlelight",
    "length_min": 3.09,
    "genre": "pop",
    "artist": "Zhavia ward",
    "year": 2018,
    "image": "images/candle.jpeg",
  },
  {
    "title": "Love Lockdown",
    "length_min": 4.30,
    "genre": "pop",
    "artist": "Kanye West",
    "year": 2018,
    "image": "images/lovelockdown.jpeg",
  },
  {
    "title": "Woke up in Japan",
    "length_min": 2.37,
    "genre": "pop",
    "artist": "5 seconds of summer",
    "year": 2018,
    "image": "images/wokeuo.jpeg",
  }
]
